baseURL = 'https://mesa-leuven.4d-star.org/tutorials/'
languageCode = 'en-us'
title = 'MESA School Leuven 2025'

theme = 'Hextra'

[params.search]
enable = false

[params.navbar.logo]
path = 'logo.png'
width = 50
height = 50

[[menu.main]]
name = 'Monday'
pageRef = '/monday/'
weight = 1

[[menu.main]]
name = 'Tuesday'
pageRef = '/tuesday/'
weight = 2

[[menu.main]]
name = 'Wednesday'
pageRef = '/wednesday/'
weight = 3

[[menu.main]]
name = 'Thursday'
pageRef = '/thursday/'
weight = 4

[[menu.main]]
name = 'Friday'
pageRef = '/friday/'
weight = 5

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['$', '$']]
